{
 "title": "CSGO (Counter-Strike: Global Offensive)",
 "description": "Dashboard for the CSGO Exporter ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "weapon",
    "label": "Weapon",
    "query": {
     "query": "label_values(csgo_total_shots_metric, name)"
    }
   },
   {
    "name": "player",
    "label": "player",
    "query": {
     "query": "label_values(csgo_playtime_metric, player_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Last Match", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Match result",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(csgo_last_match_metric{type=\"wins\", player_name=\"$player\"}) / 15",
     "legendFormat": "Result"
    }
   ]
  },
  {
   "title": "Favourite Weapon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"favweapon_id\", player_name=\"$player\"}",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "Favourite Weapon Kills",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"favweapon_kills\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Favourite Weapon Shots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"favweapon_shots\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Favourite Weapon Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"favweapon_hits\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"wins\", player_name=\"$player\"}",
     "legendFormat": "Wins"
    },
    {
     "expr": "max(csgo_last_match_metric{type=\"rounds\", player_name=\"$player\"}) without (type) - max(csgo_last_match_metric{type=\"wins\", player_name=\"$player\"}) without (type)",
     "legendFormat": "Losses"
    },
    {
     "expr": "csgo_last_match_metric{type=\"rounds\", player_name=\"$player\"}",
     "legendFormat": "Total Rounds"
    }
   ]
  },
  {
   "title": "ADR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"damage\", player_name=\"$player\"} / on (player) csgo_last_match_metric{type=\"rounds\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "KDR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"kills\", player_name=\"$player\"} / on (player) csgo_last_match_metric{type=\"deaths\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"kills\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"deaths\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "MVPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"mvps\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Money Spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_last_match_metric{type=\"money_spent\", player_name=\"$player\"}"
    }
   ]
  },
  { "title": "Inventory Market", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Inventory value",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(csgo_user_inventory_metric{marketable=\"true\", player_name=\"$player\"})"
    }
   ]
  },
  {
   "title": "Price over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "csgo_user_inventory_metric{marketable=\"true\", player_name=\"$player\"}",
     "legendFormat": "{{ market_name }}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Kills",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_kills\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_deaths\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total MVP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_mvps\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Pistol Round Wins",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_wins_pistolround\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Kills Zoomed Sniper",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_kills_against_zoomed_sniper\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Bombs Planted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_planted_bombs\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Defused Bombs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_defused_bombs\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Headshots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_kills_headshot\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Damage Done",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_damage_done\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Rounds Won",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_wins\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Kills Enemy Weapons",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_kills_enemy_weapon\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Broken Windows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_broken_windows\", player_name=\"$player\"}"
    }
   ]
  },
  { "title": "Stats by Weapon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$weapon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "repeat": "weapon",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_total_kills_metric{name=\"$weapon\", player_name=\"$player\"}",
     "legendFormat": "Kills"
    },
    {
     "expr": "csgo_total_shots_metric{name=\"$weapon\", player_name=\"$player\"}",
     "legendFormat": "Shots"
    },
    {
     "expr": "csgo_total_hits_metric{name=\"$weapon\", player_name=\"$player\"}",
     "legendFormat": "Hits"
    }
   ]
  }
 ]
}